template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "tuvi1240"
__REPO__ = "lang-tyv"
__UND2C__ = "tyv"
__UNDEFINED__ = "Tuvinian"
__UND__ = "tyv"
